# Generated by Django 5.2 on 2025-05-08 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='many_to_many',
            new_name='especialidades',
        ),
    ]
